MyBookingRoles/Controllers/Delivery/DeliverySystemController.cs
using MyBookingRoles.Models;
using MyBookingRoles.Models.Store;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBookingRoles.Controllers.Delivery
{
    [Authorize(Roles = "Delivery")]
    public class DeliverySystemController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult DeliveryDashboard()
        {
            return View(db.Orders.Where(p => p.Status.Contains("Approved")).ToList());
        }

        public ActionResult AcceptOrder(int orderID)
        {
            Order ord = db.Orders.Find(orderID);
            ord.Status = "Accepted";
            db.Entry(ord).State = EntityState.Modified;
            db.SaveChangesAsync();

            return RedirectToAction("DeliveryUserOrders", new { id = ord.OrderId });
        }

        public ActionResult DeliveryUserOrders()
        {
            return View();
        }
    }
}

MyBookingRoles/Views/DeliverySystem/DeliveryDashboard.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Delivery Dashboard";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>DeliveryDashboard</h2>

<div class="jumbotron" style="text-align: center;">
    <h1>Welocome to Delivery Dashboard</h1>
    <h4 class="lead" style="text-align: center;">
        <b><u>@User.Identity.GetUserName()</u></b>
    </h4>
    <hr />
    <div style="padding:5px; border: 1px solid black; background-color: white;" class="row">
        <p>Manage Your Account Here. As a Customer.</p>
    </div>
</div>
<hr />

<div class="row">
    <div class="container">
        <h1><u><b>Your General Options</b></u></h1>
        <br />
        <br />

        <div style="background-color: white; padding: 15px; text-align:center;" class="col-md-12">
            <div class="container">

                <p style="padding: 5px 5px; border: 1px dashed gray;" class="col-md-4">
                    @Html.ActionLink("Approved Orders", "#", "DeliverySystem", null, new { @class = "btn btn-danger" })
                    <br />
                    <br />
                    All Approved Orders
                </p>

                <p style="padding: 5px 5px; border: 1px dashed gray;" class="col-md-4">
                    @Html.ActionLink("Make A Delivery", "#", "DeliverySystem", null, new { @class = "btn btn-danger" })
                    <br />
                    <br />
                    Your Make A Delivery Here!
                </p>
                <p style="padding: 5px 5px; border: 1px dashed gray;" class="col-md-4">
                    @Html.ActionLink("My Delivered Orders", "#", "DeliverySystem", null, new { @class = "btn btn-danger" })                    <br />
                    <br />
                    Your Delivered Orders Here!
                </p>
            </div>
            <hr />
            <p>
                <h2>
                    Delete account Doesnt Work.
                </h2>
            </p>
        </div>
    </div>
</div>