MyBookingRoles/Controllers/MyUserController.cs
using Microsoft.AspNet.Identity;
using MyBookingRoles.Models;
using MyBookingRoles.Models.Store;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBookingRoles.Controllers
{
    [Authorize(Roles = "Customer")]
    public class MyUserController : Controller
    {
        private ApplicationDbContext context;

        public MyUserController()
        {
            context = new ApplicationDbContext();
        }

        // Index
        public ActionResult Index()
        {
            return View();
        }

        // UserProfile
        public ActionResult UserProfile()
        {
            return View();
        }

        //Customer List
        public ActionResult customerOrders(string searchWord)
        {
            var id = User.Identity.GetUserName().ToString();
            var mm = context.Orders.Where(v => v.CustomerEmail == id && (v.Status.Contains(searchWord) || searchWord == null)).ToList();
            ViewBag.User = id;
            return View(mm);
        }

        public ActionResult DeleteOrder(int id)
        {
            Order ord = context.Orders.Find(id);
            ord.Status = "Cancelled";

            string subject = ord.OrderName + " Status Update.";
            string body = "<b>Order : " + ord.OrderName + " Your Order Has Been Cancelled. <b /><br /><br /><hr /><b style='color: red'>Please Do not reply</b>.<br /> Thanks & Regards, <br /><b>Studio Foto45!</b>";
            ord.SendMail(subject, body);

            context.Entry(ord).State = EntityState.Modified;
            context.SaveChangesAsync();

            return RedirectToAction("Index", new { id = ord.OrderId });
        }

        public ActionResult RatingSerciveIndex()
        {
            var usr = User.Identity.GetUserName().ToString();
            var myrate_Services = context.Rate_Services.Where(b => b.Rate_ServiceUser == usr).ToList();
            return View(myrate_Services);
        }

        public ActionResult DeleteUser(string id)
        {
            var usr = context.Users.Find(id);
            return View(usr);
        }

        [HttpPost]
        [ActionName("DeleteUser")]
        public ActionResult DeleteUserConfirm(string id)
        {
            var usr = context.Users.Find(id);
            context.Users.Remove(usr);
            context.SaveChanges();
            return RedirectToAction("Login", "Account");
        }





















        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MyBookingRoles/Controllers/Stores/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyBookingRoles.Models;
using MyBookingRoles.Models.Store;

namespace MyBookingRoles.Controllers.Store
{
    public class ShoppingCartController : Controller
    {
        private ApplicationDbContext context = new ApplicationDbContext();

        // GET: ShoppingCart
        public ActionResult Cart()
        {
            ViewBag.User = User.Identity.GetUserName().ToString();
            return View();
        }

        // GET: ShoppingCart/Order Now
        public ActionResult OrderNow(int id)
        {
            //Fix Error On Cart Loading With This Expr101
            if(Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(context.Products.Find(id),1));
                Session["cart"] = cart;

                //
                ViewBag.ListCart = cart.Count();
                Session["count"] = ViewBag.ListCart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                    cart.Add(new Item(context.Products.Find(id), 1));
                else
                    cart[index].Quantity++;

                Session["cart"] = cart;
                ViewBag.ListCart = cart.Count();
                Session["count"] = ViewBag.ListCart;
            }
            
            return RedirectToAction("Cart");
        }

        //Is Existing
        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Pr.ProductID == id)
                    return i;
            return -1;
        }

        //GET: Update
        public ActionResult Update(FormCollection fc)
        {
            string[] quantity = fc.GetValues("quantity");
            List<Item> cart = (List<Item>)Session["cart"];
            
            
            for (int i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = Convert.ToInt32(quantity[i]);
                
            }
            Session["cart"] = cart;
            return RedirectToAction("Cart");
        }

        // GET: Delete
        public ActionResult Delete(int id)
        {
            //get current Id, and Cart Session
            int index = isExisting(id);

            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);

            Session["cart"] = cart;

            ViewBag.ListCart = cart.Count();
            Session["count"] = ViewBag.ListCart;
            return RedirectToAction("Cart");
        }

        [Authorize(Roles = "Customer")]
        public ActionResult CheckOut()
        {
            ViewBag.User = User.Identity.GetUserName().ToString();
            return View();
        }

        //[HttpPost]
        //Authorize to add the orders form Correctly
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public ActionResult ProcessOrder(FormCollection frc)
        {

            //Create a order model & Order Details Model
            List<Item> lstcart = (List<Item>)Session["cart"];

            //
            Order order = new Order()
            {
                PaymentAmount = System.Convert.ToDouble(frc["TotalAmount"]),
                CustomerName = frc["custName"],
                CustomerPhone = frc["custPhone"],
                CustomerEmail = frc["custEmail"],
                CustomerAddress = frc["Street"] +","+ frc["Suburb"] + "," + frc["City"] + "," + frc["Province"],
                OrderDate = DateTime.Now,
                PaymentType = "PayPal",
                Status = "Processing",
                OrderName = frc["custName"] + "-" + DateTime.Now + "-" + System.Convert.ToDouble(frc["TotalAmount"])
            };

            //Email
            string subject = "Studio Foto45 Purchase Order Details";
            string body = "Dear " + order.CustomerName + ", <br /><br />Order : <b style='color: green'>" + order.OrderName + "</b> Was Successfull! <br />Delivery to -<b>" + order.CustomerAddress + "</b>-</b><br /> Your Order Will be delivered in 6-7 Working day. Please Login to <b>Studio Foto45!</b> for your Orders.<hr /><b style='color: red'>Please Do not reply</b>.<br /> Thanks & Regards, <br /><b>Studio Foto45!</b>";
            order.SendMail(subject,body);
            
            //Db Saving
            context.Orders.Add(order);
            context.SaveChanges();
            
            ///
            foreach (Item cart1 in lstcart)
            {
                OrderDetails item1 = new OrderDetails()
                {
                    OrderId = order.OrderId,
                    ProdId = cart1.Pr.ProductID,
                    Quantity = cart1.Quantity,
                    Price = cart1.Pr.Price,
                    ProdName = cart1.Pr.ProductName
                 };

                context.OrderDetails.Add(item1);


                //Write Statement to Update product quantity on purchase
                Product prd = context.Products.Find(cart1.Pr.ProductID);
                prd.InStoreQuantity -= cart1.Quantity;
                context.Entry(prd).State = EntityState.Modified;

                
                context.SaveChanges();

            }

            Session.Remove("cart");
            Session.Remove("count");
            return View("OrderSuccess",new { ord = order.OrderName});
            //Create a Add Statement for the modes
        }

        [Authorize(Roles = "Customer")]
        public ActionResult OrderSuccess()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();

            }
            base.Dispose(disposing);
        }
    }
}

MyBookingRoles/Views/ShoppingCart/Cart.cshtml
@using MyBookingRoles.Models.Store
@{
    ViewBag.Title = "Your Shopping Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><u>Your Shopping Cart : @ViewBag.User</u></h2>
<br />
<div class="form-inline">
    @{
        decimal s = 0;
    }

    @if (ViewBag.QError != null)
    {
        <p>@ViewBag.QError</p>
    }
</div>
<br />
<div class="form-inline" id="printdivcontent">
    @using (Html.BeginForm("Update", "ShoppingCart", FormMethod.Post))
    {
    <div style="text-align: left; border-top: 2px solid black; background-color:gray; padding: 5px;">

        <input type="submit" value="Update Quantity" class="btn btn-default btn-primary" />

    </div>

        <br />
        <div class="table table-responsive table-hover table-condensed" style="border:2px solid gray; padding: 5px;">
            @if ((List<Item>)Session["cart"] != null)
            {
                foreach (var item in (List<Item>)Session["cart"])
                {
                    s = s + item.Pr.Price * item.Quantity;
                    <div class="col-md-3" style="border:1px solid black; padding: 5px;">
                        <div style="background-color: aliceblue;padding: 5px;">
                            @if (item.Pr.ProductPics != null)
                            {
                                var base64 = Convert.ToBase64String(item.Pr.ProductPics);
                                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                                <img src='@imgsrc' class="img-responsive" />
                            }
                            <p><u>@item.Pr.ProductName</u></p>

                            <p><b>Price : R @item.Pr.Price</b></p>
                            <p><input type="text" name="quantity" value="@item.Quantity" class="form-control" /> </p>
                            <p>
                                <b><u>Sub Total : R @(item.Pr.Price * item.Quantity)</u></b>
                            </p>
                            <p>@Html.ActionLink("Remove Item", "Delete", "ShoppingCart", new { id = item.Pr.ProductID }, new { @class = "btn btn-danger" })</p>
                        </div>

                    </div>

                }
            }
            else
            {
                <div class="col-md-6" style="border:1px solid black; padding: 5px;">
                    <p style="background-color: aliceblue;padding: 5px;">
                        <h3>Please Add Products To Cart From the Catalogue.</h3>
                    </p>
                </div>
            }
        </div>
        <br />
        <p>
            <h3 style="background-color: gray;">
                Total Amount : <b>R @s</b>
            </h3>
        </p>
    }
    <hr />
    <div class="form-inline">
        @Html.ActionLink("Continue Shopping!", "ProdCatalogue", "Store", null, new { @class = "btn btn-default" }) |


        @if (User.Identity.IsAuthenticated)
        {
            if (s != 0)
            {
                @Html.ActionLink("Check-Out!", "CheckOut", "ShoppingCart", null, new { @class = "btn btn-success" });
            }
            else
            {
                @Html.ActionLink("Add Items To Your Cart", "ProdCatalogue", "Store", null, new { @class = "btn btn-primary" })
            }
        }
        else
        {
            @*<span class="btn btn-danger">You must be Logged in To Check-Out.</span>*@
            @Html.ActionLink("Please Log in to Check-Out", "Login", "Account", routeValues: null, htmlAttributes: new { @class = "btn btn-danger" })

            @*<button type="button" onclick="PrintDiv();" class="btn btn-default pull-right">Print Order.</button>*@
        }
    </div>
</div>
@*<script type="text/javascript">
    function PrintDiv() {
        var divContents = document.getElementById("printdivcontent").innerHTML;
        var printWindow = window.open('', '', 'height=800,width=1000');
        printWindow.document.write('<html><head><title>Print DIV Content</title>');
        printWindow.document.write('</head><body >');
        printWindow.document.write(divContents);
        printWindow.document.write('</body></html>');
        printWindow.document.close();
        printWindow.print();
    }
</script>*@

MyBookingRoles/Views/ShoppingCart/CheckOut.cshtml
@using MyBookingRoles.Models.Store

@{
    ViewBag.Title = "Check-Out";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><u>Check-Out : @ViewBag.User</u></h2>

@{
    decimal s = 0;
}
<div class="form-inline">
    <h2>Your Ordered Products</h2>
    <table class="table table-responsive table-hover table-condensed">
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub</th>
            <th>Discount Price</th>
            <th style="text-align:center; background-color: gray;">Operations</th>
        </tr>
        @if ((List<Item>)Session["cart"] != null)
        {
            foreach (var item in (List<Item>)Session["cart"])
            {
                s = item.Price + item.Pr.Price * item.Quantity;
                <tr>
                    <td>@item.Pr.ProductName</td>
                    <td>R @item.Pr.Price</td>
                    <td>@item.Quantity</td>
                    <td>
                        R @(item.Pr.Price * item.Quantity)
                    </td>
                    <td></td>
                    <td style="text-align:center;">@Html.ActionLink("Remove Item", "Delete", "ShoppingCart", new { id = item.Pr.ProductID }, new { @class = "btn btn-danger" })</td>
                </tr>
            }
        }
        else
        {
            <tr class="row">
                <td style="background-color: red;">
                    <h3>Check-Out Empty .</h3>
                    <p>
                        @Html.ActionLink("Go Back Shopping!", "ProdCatalogue", "Store")
                    </p>
                </td>
            </tr>
        }
    </table>
    <br />
    <p>
        <h3 >
            Total Amount : R @s
        </h3>
    </p>

    <br />
    <br />
    @*<ul>
        <li>Add user Address full Details</li>
    </ul>*@
    @if (s != 0)
    {
        <div class="form-inline">
            @using (Html.BeginForm("ProcessOrder", "ShoppingCart", FormMethod.Post, new { id = "customerform" }))
            {
                <table class="table table-responsive table-condensed">
                    <tr>
                        <td colspan="2" style="text-align: center; background-color: gray;"><h3><u>Delivery Address</u></h3></td>
                    </tr>
                    <tr>
                        <td>Total Amount</td>
                        <td>R <input type="text" name="TotalAmount" value="@s" readonly class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Customer Name</td>
                        <td>&nbsp; &nbsp; <input type="text" name="custName" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Customer Phone</td>
                        <td>&nbsp; &nbsp; <input type="text" name="custPhone" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Customer Email</td>
                        <td>&nbsp; &nbsp; <input type="text" name="custEmail" readonly value="@ViewBag.User" class="form-control" /></td>
                    </tr>
                    <tr>
                        <td colspan="2" style="text-align: center; background-color: gray;"><h3><u>Delivery Address</u></h3></td>
                        
                    </tr>
                    <tr>
                        <td>Street</td>
                        <td>&nbsp; &nbsp; <input type="text" name="Street" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Suburb</td>
                        <td>&nbsp; &nbsp; <input type="text" name="Suburb" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td>&nbsp; &nbsp; <input type="text" name="City" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Province</td>
                        <td>&nbsp; &nbsp; <input type="text" name="Province" required class="form-control" /></td>
                    </tr>
                    <tr>
                        <td>Country</td>
                        <td>&nbsp; &nbsp; <input type="text" name="Country" required class="form-control" /></td>
                    </tr>
                    
                </table>
                <hr />
                <div class="form-group" >
                    
                    <br />
                    <input type="submit" value="Process Order" class="btn btn-success" />
                </div>
            }
        </div>

        <hr />
        <div class="row">
            @Html.ActionLink("Go Back Shopping!", "ProdCatalogue", "Store", null, new { @class = "btn btn-default pull-left" })
            
            @*@Html.ActionLink("Save Shopping Cart!", "#", "#", null, new { @class = "btn btn-danger" }) | 
            @Html.ActionLink("View Saved Shoppings!", "#", "#", null, new { @class = "btn btn-danger" })*@
        </div>
    }
</div>

MyBookingRoles/Views/ShoppingCart/OrderSuccess.cshtml
@{
    ViewBag.Title = "OrderSuccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2><u>Thank you For Ordering at <b>Studio Foto45</b></u></h2>
<p>
    Your Order Will be delivered in 6-7 Working day. &nbsp;
    Please Check Your Email For Updates.
</p>

<div class="form-inline">
    <h3>
        Your Order is being Processed.  @Html.ActionLink("Click Here!", "customerOrders", "MyUser",null,new { @class = "btn btn-success"}) for your Orders.
    </h3>
    <p>
        Go Back to @Html.ActionLink("Store Catalogue!", "ProdCatalogue", "Store")
        <br />

    </p>
    <p>
        @Html.ActionLink("Go Back Your Dashboard!", "Index", "MyUser")
    </p>
</div>